### ISSUE TITLE
Executable checkbox disables after deleting diagram with pool

### ISSUE THREAD

**Issue by Camundaan** [camunda/camunda-bpmn-js#149] opened 2022-07-26 13:53 UTC
__Describe the Bug__
After deleting the last pool with a working diagram in the WebModeler, the "executable" checkbox is automatically disabled and stays disabled even after creating an error-free diagram after that.

__Steps to Reproduce__
[Recording](https://camunda.zoom.us/rec/share/h4dGA-CwwBH2yDd7zk-tP1YsMkYZ380nxMV4i0DfK8QXGFS7apPuH7pCTXXGKxNn.tXcc6rugO7gZ8ZK-?startTime=1658740206000)
Passcode: c@4R?Sp*

1. Create a working diagram in a pool
2. Delete pool 
3. Checkbox "executable" is disabled and stays disabled even when users create a new working, error-free diagram.

__Expected Behavior__
Users would expect the executable checkbox to be automatically enabled again when creating a new diagram, with or without a pool.

__Environment__
WebModeler
- OS: [e.g. MacOS 10.2, Windows 10]
- Modeler version: [e.g. 2.0.0]

**Comment by marstamm** [comment] 2022-07-28 14:29
I can reproduce this also on latest modeler release.

**Root Cause**

When the last participant is deleted, bpmn-js replaces the collaboration with an empty process without any execution semantics.

This might be a case to be fixed in https://github.com/camunda/camunda-bpmn-js-behaviors to keep the config of the last Process

**Comment by christian-konrad** [comment] 2022-07-29 13:09
@marstamm can I add this to ready, so we can discuss this in the next planning?

**Comment by marstamm** [comment] 2022-07-29 14:46
@christian-konrad, I moved it to ready. You can move any issue to ready that you want to discuss in the next planning meeting. no need to check in first :)

**Comment by pinussilvestrus** [comment] 2022-09-02 14:19
Closed via https://github.com/camunda/camunda-bpmn-js/commit/293586560c538bfbad9431b2dedf20ebda42883a

**Closed by pinussilvestrus** 2022-09-02 14:19 UTC
Labels: bug, needs review, spring cleaning
