### ISSUE TITLE
`Cannot read properties of undefined (reading 'clientWidth')`

### ISSUE THREAD

**Issue by boris-petrov** [camunda/camunda-bpmn-js#114] opened 2022-04-12 14:09 UTC
__Describe the Bug__

Stack trace:

```
Canvas.getSize	@	Canvas.js:1391
Canvas.viewbox	@	Canvas.js:1096
Canvas._viewboxChanged	@	Canvas.js:1039
fire	@	index.esm.js:413
setTimeout (async)		
schedule	@	index.esm.js:418
callback	@	index.esm.js:448
Canvas._changeViewbox	@	Canvas.js:1035
Canvas.scroll	@	Canvas.js:1166
(anonymous)	@	align-to-origin.js:151
wrappedCallback	@	EventBus.js:185
invokeFunction	@	EventBus.js:519
EventBus._invokeListener	@	EventBus.js:371
EventBus._invokeListeners	@	EventBus.js:352
EventBus.fire	@	EventBus.js:313
CommandStack._fire	@	CommandStack.js:356
CommandStack._popAction	@	CommandStack.js:470
CommandStack.execute	@	CommandStack.js:154
align	@	align-to-origin.js:102
invokeFunction	@	EventBus.js:519
EventBus._invokeListener	@	EventBus.js:371
EventBus._invokeListeners	@	EventBus.js:352
EventBus.fire	@	EventBus.js:313
BaseViewer._emit	@	BaseViewer.js:651
(anonymous)	@	BaseViewer.js:370
saveXML	@	BaseViewer.js:361
(anonymous)	@	CompatibilityUtil.js:53
```

I migrated from using "manually" `bpmn-js` and registering Camunda's plugins to using `camunda-bpmn-js`. My tests hit this exception. The use case is as follows - I call `saveXML`, then (after it has finished), I call `modeler.destroy()`. Then the exception happens - obviously `saveXML` schedules something to be executed but it executes after `destroy` has been called and that fails.

__Steps to Reproduce__

Call `saveXML`, then call `modeler.destroy()` - should happen.

__Expected Behavior__

No exception.

__Environment__

- OS: Linux
- Modeler version: 0.13.0-alpha.8

**Comment by MaxTru** [comment] 2022-04-13 09:54
I can reproduce this, but also without calling `saveXML`. See [codeSandbox](https://codesandbox.io/s/camunda-bpmn-js-bug-reproduction-00iiug?file=/src/index.js)

**Comment by MaxTru** [comment] 2022-04-13 09:56
Reproduced, moving to backlog and also marking for springCleaning

**Comment by MaxTru** [comment] 2022-04-13 14:24
First root causing:
* This bug is caused by the [align-to-origin](https://github.com/bpmn-io/align-to-origin) module, which is included as part of this distribution (see [here](https://github.com/camunda/camunda-bpmn-js/blob/main/lib/base/Modeler.js#L33))
* The same bug also appears, when bpmn-js, and align to origin module are loaded and destroy is called. E.g.:
```
...

import AlignToOrigin from '@bpmn-io/align-to-origin';



var bpmnModeler = new BpmnModeler({
  container: canvas,
  propertiesPanel: {
    parent: '#js-properties-panel'
  },
  additionalModules: [
    BpmnPropertiesPanelModule,
    BpmnPropertiesProviderModule,
    AlignToOrigin
  ]
});
```

**Comment by marstamm** [comment] 2024-05-28 08:34
I can not reproduce this anymore: https://codesandbox.io/p/sandbox/reproduction-j56r4v

**Closed by marstamm** 2024-05-28 08:34 UTC
Labels: bug, spring cleaning
