### ISSUE TITLE
Exceptions when BPMN modeler contains subprocess

### ISSUE THREAD

**Issue by spalberg** [camunda/camunda-bpmn-js#132] opened 2022-06-03 14:29 UTC
__Describe the Bug__

As soon as the BPMN loaded by the modeler (we tested the cloud modeler) contains a subprocess bpmn element, the exceptions appear in the browsers console. 
The first exception is this one: 
`unhandled error in event listener Error: invalid hit type <no-move>`
The subprocess is also not clickable/interactive afterwards.
![image](https://user-images.githubusercontent.com/22957596/171874399-127bcac6-daaa-4488-9dd7-ec18c102fe7b.png)

__Steps to Reproduce__

1. Clone this repository (current commit is https://github.com/camunda/camunda-bpmn-js/commit/86de66dd856a50295606bf30e0cfea7979948178)
2. Install dependencies (`npm install`)
3. Start `npm run start:cloud`
4. Place a subprocess in the bpmn modeler

__Expected Behavior__

No exceptions should be thrown and the subprocess should behave like any other bpmn element.

__Environment__

- OS: [Windows 10, Linux]
- NPM: 8.5.0
- Node: 16.14.2

**Comment by pinussilvestrus** [comment] 2022-06-06 13:25
Hi @spalberg! I can verify this on my machine, thanks for reporting!

I'm moving this to ready as it seems it's related to some recent changes (cf. [bpmn-js 9.1.0 Changelog](https://github.com/bpmn-io/bpmn-js/blob/develop/CHANGELOG.md#910)).

**Comment by pinussilvestrus** [comment] 2022-06-07 07:28
When linking `bpmn-js#develop` the issue is resolved, there this is pending releasing and integrating `bpmn-js@9.2.0`.

**Comment by nikku** [comment] 2022-06-07 11:24
Closed via https://github.com/camunda/camunda-bpmn-js/pull/133.

As you use newer versions of bpmn-js, ensure you bump diagram-js versions to latest, too.

**Closed by nikku** 2022-06-07 11:24 UTC
Labels: bug, needs review
